//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace substransferV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_upacking_data_dbEntities : DbContext
    {
        public siixsem_upacking_data_dbEntities()
            : base("name=siixsem_upacking_data_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getSerialPCBByCov_Result> getSerialPCBByCov(string serial, string tblCov)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            var tblCovParameter = tblCov != null ?
                new ObjectParameter("tblCov", tblCov) :
                new ObjectParameter("tblCov", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSerialPCBByCov_Result>("getSerialPCBByCov", serialParameter, tblCovParameter);
        }
    }
}
