//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace substransferV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_upacking_config_dbEntities : DbContext
    {
        public siixsem_upacking_config_dbEntities()
            : base("name=siixsem_upacking_config_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getModelConfig_Result> getModelConfig(Nullable<int> idModelDet)
        {
            var idModelDetParameter = idModelDet.HasValue ?
                new ObjectParameter("idModelDet", idModelDet) :
                new ObjectParameter("idModelDet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getModelConfig_Result>("getModelConfig", idModelDetParameter);
        }
    
        public virtual ObjectResult<getModelByCustomerNo_Result> getModelByCustomerNo(string custNo)
        {
            var custNoParameter = custNo != null ?
                new ObjectParameter("CustNo", custNo) :
                new ObjectParameter("CustNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getModelByCustomerNo_Result>("getModelByCustomerNo", custNoParameter);
        }
    }
}
